import os
from datetime import datetime

LOG_DIR = "logs"

def save_tool_output(tool_name: str, input_text: str, output_text: str):
    """
    Saves the tool input and output to a markdown file in a readable, well-formatted style.

    The output markdown includes:
    - Tool name and timestamp
    - Input wrapped in a generic code block (no language tag)
    - Output pasted as-is (respects markdown format directly)
    - Separator between runs

    Args:
        tool_name (str): The name of the tool that ran
        input_text (str): The input given to the tool
        output_text (str): The output generated by the tool
    """
    # Ensure log directory exists
    os.makedirs(LOG_DIR, exist_ok=True)

    # Define file path
    filename = f"{tool_name}_result.md"
    filepath = os.path.join(LOG_DIR, filename)

    # Get current timestamp
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Write to file in append mode
    with open(filepath, "a", encoding="utf-8") as f:
        f.write(f"# Tool Run - {tool_name}\n")
        f.write(f"**Timestamp:** {timestamp}\n\n")

        f.write("## Input\n")
        f.write("```\n")
        f.write(input_text.strip())
        f.write("\n```\n\n")

        f.write("## Output\n")
        f.write(output_text.strip())
        f.write("\n\n")

        f.write("---\n\n")  # Separator for multiple runs

    print(f"[MarkdownLogger] Saved output to {filepath}")